# Generated by Django 5.2.6 on 2025-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('clothes', 'Clothes'), ('transport', 'Transport'), ('others', 'Others')], max_length=100),
        ),
    ]
