# Generated by Django 5.2.6 on 2025-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensecategory_custom_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(),
        ),
    ]
