# Generated by Django 5.2.6 on 2025-09-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_budget_updated_at_alter_budget_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='custom_name',
        ),
    ]
