# Generated by Django 5.1.4 on 2025-11-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_budgetcategories_category_notification_savingsgoals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
